version: "2.1"
services:
  mongo:
    image: mongo:latest
    ports:
    - 27017:27017
    command: --smallfiles
      
  mongo-client:
    image: mongoclient/mongoclient
    ports:
    - 3030:3030
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=localhost://mongo:27017
    links:
      - mongo
    
# APP  ***************************************************************************************
  spring-boot-mongo-docker:
    image: springio/gs-accessing-data-mongodb
    ports:
    - 8080:8080
    links:
    - mongo
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"